# Generated by Django 4.0.3 on 2022-07-17 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='closed',
            new_name='close',
        ),
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.URLField(blank=True, max_length=5000),
        ),
    ]
