# Generated by Django 4.0.3 on 2022-07-17 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_rename_closed_auction_close_alter_auction_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='seller',
            new_name='user',
        ),
    ]
